# ============================================================================
# BLACK - Formatage du code
# ============================================================================
[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.mypy_cache
  | \.pytest_cache
  | \.ruff_cache
  | \.venv
  | venv
  | build
  | dist
  | __pycache__
  | alexa_auth/nodejs
  | scripts
  | \.git
  | __pycache__
  | venv
  | \.venv
  | \.mypy_cache
  | \.pytest_cache
  | \.ruff_cache
  | build
  | dist
  | \.tox
  | \.eggs
  | \*\.egg
)/
'''

# ============================================================================
# ISORT - Organisation des imports
# ============================================================================
[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip_gitignore = true
skip = [
    ".git",
    "__pycache__",
    "venv",
    "alexa_auth/nodejs",
    "scripts",
    ".git",
    "__pycache__",
    "venv",
    ".venv",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "build",
    "dist",
    ".tox",
    ".eggs",
    "*.egg"
]

# ============================================================================
# PYLINT - Analyse de code avancée
# ============================================================================
[tool.pylint.main]
py-version = "3.8"
jobs = 0
fail-under = 10.0
ignore-paths = [
    "scripts",
    ".git",
    "__pycache__",
    "venv",
    ".venv",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "build",
    "dist",
    ".tox",
    ".eggs",
    "*.egg"
]

[tool.pylint.messages_control]
disable = [
    "duplicate-code",
    "fixme",
    "too-few-public-methods",
    "import-outside-toplevel",
    "broad-exception-caught",
]

[tool.pylint.format]
max-line-length = 100
max-module-lines = 1000

[tool.pylint.design]
max-args = 8
max-attributes = 15
max-branches = 15
max-locals = 20
max-statements = 60

# ============================================================================
# RUFF - Linter moderne
# ============================================================================
[tool.ruff]
line-length = 100
target-version = "py38"
select = ["E", "W", "F", "I", "N", "UP", "B", "C4", "SIM"]
ignore = ["E501"]
exclude = [
    "scripts",
    ".git",
    "__pycache__",
    "venv",
    ".venv",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "build",
    "dist",
    ".tox",
    ".eggs",
    "*.egg",
    "alexa_auth/nodejs"
]

# ============================================================================
# COVERAGE - Couverture de code
# ============================================================================
[tool.coverage.run]
source = ["core", "utils", "api", "cli", "scripts"]
omit = ["*/tests/*", "*/__pycache__/*", "*/venv/*"]

[tool.coverage.report]
precision = 2
show_missing = true
skip_covered = false
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]

# ============================================================================
# FLAKE8 - Align flake8 with Black's formatting decisions
# ============================================================================
[tool.flake8]
max-line-length = 100
extend-ignore = ["E203", "W503"]
exclude = [
    ".git",
    "__pycache__",
    "venv",
    ".venv",
    "alexa_auth/nodejs",
    "build",
    "dist",
]


[tool.pytest.ini_options]
testpaths = ["tests"]
# Use conventional pytest discovery
python_files = ["test_*.py", "*_test.py"]
# Show extra summary and keep quiet on passing tests; keep maxfail
addopts = "-q --disable-warnings --maxfail=1 -ra"
