[tool.vulture]
exclude = [
    "venv",
    ".venv",
    "__pycache__",
    ".mypy_cache",
    ".pytest_cache",
    ".ruff_cache",
    "build",
    "dist",
    ".tox",
    ".eggs",
    "*.egg",
    "scripts",
    ".git",
    "alexa_auth/nodejs"
]
