name: Python CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.11, 3.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -r requirements-dev.txt
      - name: Run tests with coverage
        run: |
          python -m pytest -q --disable-warnings --maxfail=1 --cov=scripts --cov-report=term-missing
      - name: Run vulture (dead code detection)
        run: |
          python -m pip install vulture==2.5
          vulture . --config .vulture.toml
