name: Python CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.11, 3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt
          elif [ -f requirements.txt ]; then pip install -r requirements.txt
          else
            echo "No requirements files"
          fi

      - name: Run tests
        run: |
          pytest -q || true

      - name: Run vulture (dead code detection)
        if: runner.os != 'Windows'
        run: |
          if [ -f .vulture.toml ]; then python -m pip install vulture==2.5; vulture . --config .vulture.toml; else echo "No .vulture.toml"; fi
